# Generated by Django 2.0 on 2019-09-09 01:37

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassifiedAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_title', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='Unit(e.g Kg, Pc, Etc', max_length=30)),
                ('tags', models.CharField(max_length=30)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_products', models.CharField(max_length=200)),
                ('image1', models.ImageField(default='', upload_to='')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_discount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classifiedadscategory', to='administrator.Category')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_title', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='Unit(e.g Kg, Pc, Etc', max_length=31)),
                ('tags', models.CharField(max_length=30)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_products', models.CharField(max_length=200)),
                ('image1', models.ImageField(default='', upload_to='')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_discount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='featured_productscategory', to='administrator.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='administrator.Category')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_title', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='Unit(e.g Kg, Pc, Etc', max_length=30)),
                ('tags', models.CharField(max_length=30)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_products', models.CharField(max_length=200)),
                ('image1', models.ImageField(default='', upload_to='')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_discount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendorcategory', to='administrator.Category')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendorsubcategory', to='administrator.SubCategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendoruser', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_related_name', to='account.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='featuredproducts',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='featured_productssubcategory', to='administrator.SubCategory'),
        ),
        migrations.AddField(
            model_name='featuredproducts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_productsuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuredproducts',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='featured_products_name', to='account.Vendor'),
        ),
        migrations.AddField(
            model_name='classifiedads',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classifiedadssubcategory', to='administrator.SubCategory'),
        ),
        migrations.AddField(
            model_name='classifiedads',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiedadsuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classifiedads',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classifiedads_related_name', to='account.Vendor'),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='administrator.Category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_subcategory', to='administrator.SubCategory'),
        ),
    ]
