# Generated by Django 2.0 on 2019-09-10 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20190910_0546'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('phone_number', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('cart', models.ManyToManyField(related_name='order_cart', to='cart.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
