# Generated by Django 2.0 on 2019-09-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190910_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('payment on delivery', 'payment on delivery'), ('online payment', 'online payment')], default='payment on delivery', max_length=30),
            preserve_default=False,
        ),
    ]
