# Generated by Django 2.0 on 2019-09-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190910_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.TextField(default='110011'),
            preserve_default=False,
        ),
    ]
