# Generated by Django 2.0 on 2019-09-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190909_0330'),
        ('cart', '0005_auto_20190910_0546'),
        ('order', '0006_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_vendor', to='account.Vendor'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='cart.Cart'),
            preserve_default=False,
        ),
    ]
