# Generated by Django 2.0 on 2019-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_createprofie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createprofie',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000000000000),
        ),
        migrations.AddField(
            model_name='createprofie',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
