# Generated by Django 2.0 on 2019-08-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190806_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='percentagerate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
