# Generated by Django 2.0 on 2019-09-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='banner',
            field=models.ImageField(default='default.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(default='default.jog', upload_to=''),
            preserve_default=False,
        ),
    ]
