# Generated by Django 2.0 on 2019-09-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190909_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='banner',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
