# Generated by Django 2.0 on 2019-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_investmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
