# Generated by Django 2.0 on 2019-08-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_investmentmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000000000000),
        ),
    ]
