# Generated by Django 2.0 on 2019-08-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_investmentmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
