# Generated by Django 2.0 on 2019-09-04 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_investmentmodel_percentagerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentmodel',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='createprofie',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='createprofie',
            name='date',
        ),
        migrations.AddField(
            model_name='createprofie',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createprofie',
            name='address_line_1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createprofie',
            name='address_line_2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createprofie',
            name='country',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createprofie',
            name='state',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createprofie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InvestmentModel',
        ),
    ]
