# Generated by Django 2.0 on 2019-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190904_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='createprofie',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
