# Generated by Django 2.0 on 2019-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_createprofie_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createprofie',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
