# Generated by Django 2.0 on 2019-09-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='username',
        ),
    ]
