# Generated by Django 2.0 on 2019-09-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='vendor',
            field=models.CharField(max_length=101),
        ),
    ]
