# Generated by Django 2.0 on 2019-09-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190909_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='single_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=15),
            preserve_default=False,
        ),
    ]
