# Generated by Django 2.0 on 2019-09-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Vendor'),
        ),
    ]
